# operation
OPERATION=sync-issue

# required parameters
SUPPORT_PROJECT=
SUPPORT_NEW_STATUS=
SUPPORT_IN_PROGRESS_STATUS=
SUPPORT_ON_HOLD_STATUS=
SUPPORT_CLOSED_STATUS=
INTERNAL_PROJECT=
INTERNAL_NEW_STATUS=
INTERNAL_IN_PROGRESS_STATUS=
INTERNAL_ON_HOLD_STATUS=
INTERNAL_CLOSED_STATUS=
SUPPORT_WATCHER=
REDMINE_TOKEN=
REDMINE_URL=

# internal parameters
LAST_CHECK_TIME=
